apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: volumesmusthavevolumemounts
spec:
  crd:
    spec:
      names:
        kind: VolumesMustHaveVolumeMounts
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package volumes_must_have_volumemounts

        violation[{"msg": msg, "details": {"missingVolumeMounts": missingVolumeMounts}}] {
          volume := input.review.object.spec.volumes[_]
          missingVolumeMounts := {volume.name | not volume_mount_defined(volume.name)}
          count(missingVolumeMounts) > 0
          msg := sprintf("Volumes have no corresponding volumeMounts: %v", [missingVolumeMounts])
        }

        volume_mount_defined(volume_name) {
          container := input.review.object.spec.containers[_]
          volumeMount := container.volumeMounts[_]
          volumeMount.name == volume_name
        }
