apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyLatestTag
metadata:
  name: disallow-latest-tag
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
      - apiGroups: ["apps"]
        kinds: ["ReplicaSet"]
      - apiGroups: ["apps.openshift.io"]
        kinds: ["DeploymentConfig"]
    excludedNamespaces:
      - "default"
      - "openshift-*"
