apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ReservedNamespace
metadata:
  name: reserved-namespace-constraint
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"] # Add other kinds as needed
      - apiGroups: ["apps"]
        kinds: ["Deployment"]  
    excludedNamespaces: ["kube-system", "gatekeeper-system"]  # Optionally exclude system namespaces
