apiVersion: constraints.gatekeeper.sh/v1beta1
kind: VolumesMustHaveVolumeMounts
metadata:
  name: enforce-volumes-must-have-volumemounts
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
      - apiGroups: ["apps.openshift.io"]
        kinds: ["DeploymentConfig"]
    excludedNamespaces:
      - "default"
      - "openshift-*"
