apiVersion: constraints.gatekeeper.sh/v1beta1
kind: VolumesWithoutMounts
metadata:
  name: check-volumes-without-mounts
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedNamespaces:
      - "test123"
      - "your-namespace"
